-- ============================================
-- 1. USER PROFILES TABLE
-- ============================================
-- Stores additional user information beyond auth.users
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- User Information
  full_name text,
  email text,
  avatar_url text
);

-- Enable RLS on profiles
alter table public.profiles enable row level security;

-- Profiles policies
create policy "Users can view their own profile"
  on public.profiles for select
  using ( auth.uid() = id );

create policy "Users can update their own profile"
  on public.profiles for update
  using ( auth.uid() = id );

create policy "Users can insert their own profile"
  on public.profiles for insert
  with check ( auth.uid() = id );

-- ============================================
-- 2. TASKS TABLE
-- ============================================
-- Stores user tasks for productivity tracking
create table public.tasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Links to user
  user_id uuid references auth.users on delete cascade not null,
  
  -- Task details
  title text not null,
  description text,
  status text default 'pending' check (status in ('pending', 'in_progress', 'completed', 'cancelled')),
  priority text default 'medium' check (priority in ('low', 'medium', 'high', 'urgent')),
  due_date timestamp with time zone,
  
  -- Task metadata
  estimated_minutes int,
  actual_minutes int,
  tags text[]
);

-- Enable RLS on tasks
alter table public.tasks enable row level security;

-- Tasks policies
create policy "Users can view their own tasks"
  on public.tasks for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own tasks"
  on public.tasks for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own tasks"
  on public.tasks for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own tasks"
  on public.tasks for delete
  using ( auth.uid() = user_id );

-- ============================================
-- 3. OPTIMIZATIONS TABLE
-- ============================================
-- This acts as a log of every schedule the user commits to.
create table public.optimizations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Links to Supabase Auth (Security)
  user_id uuid references auth.users on delete cascade not null,
  
  -- The Input (So they can re-run later)
  input_text text,
  
  -- The Schedules (Stored as JSON so we can add fields like 'rationale' easily)
  original_schedule jsonb, 
  optimized_schedule jsonb,
  
  -- The Scoreboard (KPIs)
  efficiency_gain_min int,        -- Total minutes saved
  context_switch_reduction int    -- Total switches removed (e.g. 12 -> 4)
);

-- Enable Security (Row Level Security)
-- This ensures User A cannot see User B's schedules.
alter table public.optimizations enable row level security;

-- Optimizations policies
create policy "Users can view their own optimizations"
  on public.optimizations for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own optimizations"
  on public.optimizations for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own optimizations"
  on public.optimizations for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own optimizations"
  on public.optimizations for delete
  using ( auth.uid() = user_id );

-- ============================================
-- 4. TRIGGERS FOR UPDATED_AT
-- ============================================
-- Function to update updated_at timestamp
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

-- Apply to profiles
create trigger on_profile_updated
  before update on public.profiles
  for each row
  execute procedure public.handle_updated_at();

-- Apply to tasks
create trigger on_task_updated
  before update on public.tasks
  for each row
  execute procedure public.handle_updated_at();

-- ============================================
-- 5. FUNCTIONS
-- ============================================
-- The Global Counter Function
-- This lets you show "Humanity has saved X hours" on the landing page
-- without exposing anyone's private data.
create or replace function get_global_saved_minutes()
returns integer
language sql
security definer
as $$
  select coalesce(sum(efficiency_gain_min), 0) from public.optimizations;
$$;